In [5]:
import torch
from torch import Tensor
from torch.nn import functional as F

In [40]:
def zero_pad(inp: Tensor):
    old_shape = inp.shape
    res = torch.zeros((old_shape[0] + 2, old_shape[1] + 2))
    res[1:-1, 1:-1] += inp
    return res

In [43]:
def calculate_output_shape(input_shape: torch.Size, filter_shape: torch.Size):
    def calc(inp, filt):
        return inp - filt + 1
    return calc(input_shape[0], filter_shape[0]), calc(input_shape[1], filter_shape[1])

In [ ]:
def

In [61]:
# setup
input = Tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
input = zero_pad(input)
filter = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
res = torch.zeros(calculate_output_shape(input.shape, filter.shape))
res

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [76]:
# convolution
for i in range(res.shape[0]):
    for k in range(res.shape[1]):
        res[i, k] = torch.sum(input[i: i + filter.shape[0],
                              k: k + filter.shape[1]]
                              * filter)

In [77]:
# pooling
res

tensor([[111., 178., 217., 145.],
        [231., 348., 393., 252.],
        [363., 528., 573., 360.],
        [197., 274., 295., 175.]])

In [64]:
a = Tensor([[1, 2, 3], [4, 5, 6]])
b = Tensor([[1, 0, 2], [0, 1, 0]])

In [74]:
torch.sum(a * b)

tensor(12.)

In [75]:
a * b

tensor([[1., 0., 6.],
        [0., 5., 0.]])